var menu_buttons = [
	{
		'btn_title':'Faciales',
		'class':'circle',
		'icon':'icon-user',
		'dir_url':'#faciales',
		'toggle':'modal',
		'target':'#myModal'
	},
	{
		'btn_title':'Corporales',
		'class':'circle',
		'icon':'icon-accessibility',
		'dir_url':'#corporales',
		'toggle':'modal',
		'target':'#myModal'
	},
	{
		'btn_title':'Antes & Despues',
		'class':'circle',
		'icon':'icon-users',
		'id':'open-popup',
		'dir_url':'#',
		'toggle':'',
		'target':''
	},
	{
		'btn_title':'Preguntas',
		'class':'circle',
		'icon':'icon-bubbles2',
		'dir_url':'#preguntas',
		'toggle':'modal',
		'target':'#myModal'
	},
	{
		'btn_title':'Certificaciones',
		'class':'circle',
		'icon':'icon-library',
		'dir_url':'#certificaciones',
		'toggle':'modal',
		'target':'#myModal'
	},
	{
		'btn_title':'Donde estoy',
		'class':'circle',
		'icon':'icon-location',
		'dir_url':'#ubicacion',
		'toggle':'modal',
		'target':'#myModal'
	},
	{
		'btn_title':'instagram',
		'id':'fotos',
		'icon':'icon-instagram',
		'dir_url':'#instagram',
		'toggle':'modal',
		'target':'#myModal'
	},
	{
		'btn_title':'Fanpage',
		'class':'circle',
		'icon':'icon-facebook',
		'dir_url':'#fanpage',
		'toggle':'modal',
		'target':'#myModal'
	},
	{
		'btn_title':'twitter',
		'class':'circle',
		'icon':'icon-twitter',
		'dir_url':'#twitter',
		'toggle':'modal',
		'target':'#myModal'
	},
	{
		'btn_title':'Contacto',
		'class':'circle',
		'icon':'icon-envelop',
		'dir_url':'#contacto',
		'toggle':'modal',
		'target':'#myModal'
	}
];