var menu_buttons = [
	{
		'btn_title':'Faciales',
		'class':'circle',
		'icon':'icon-user',
		'dir_url':'#faciales'
	},
	{
		'btn_title':'Corporales',
		'class':'circle',
		'icon':'icon-accessibility',
		'dir_url':'#corporales'
	},
	{
		'btn_title':'Preguntas',
		'class':'circle',
		'icon':'icon-bubbles2',
		'dir_url':'#preguntas'
	},
	{
		'btn_title':'Certificaciones',
		'class':'circle',
		'icon':'icon-checkmark',
		'dir_url':'#certificaciones'
	},
	{
		'btn_title':'Antes & Despues',
		'class':'circle',
		'icon':'icon-users',
		'dir_url':'#antes-despues'
	},
	{
		'btn_title':'Donde estoy',
		'class':'circle',
		'icon':'icon-location',
		'dir_url':'#ubicacion'
	},
	{
		'btn_title':'instagram',
		'id':'fotos',
		'icon':'icon-instagram',
		'dir_url':'#instagram'
	},
	{
		'btn_title':'Fanpage',
		'class':'circle',
		'icon':'icon-facebook',
		'dir_url':'#fanpage',
	},
	{
		'btn_title':'twitter',
		'class':'circle',
		'icon':'icon-twitter',
		'dir_url':'#twitter',
	},
	{
		'btn_title':'Contacto',
		'class':'circle',
		'icon':'icon-envelop',
		'dir_url':'#contacto'
	}
];